new project

diff --git a/.github/workflows/trigger-api-tests.yml b/.github/workflows/trigger-api-tests.yml
--- a/.github/workflows/trigger-api-tests.yml
+++ b/.github/workflows/trigger-api-tests.yml
@@ -1,19 +1,15 @@
-name: Trigger API Automation
+- name: Trigger Automation Repo
+  run: |
+    RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST \
+      -H "Accept: application/vnd.github+json" \
+      -H "Authorization: Bearer ${{ secrets.API_TEST_TRIGGER_TOKEN }}" \
+      https://api.github.com/repos/roshaniwagh/api.swagh.in/dispatches \
+      -d '{"event_type":"run-api-tests"}')
 
-on:
-  push:
-    branches:
-      - master   # change to main if needed
+    echo "HTTP Status: $RESPONSE"
+    cat response.txt
 
-jobs:
-  trigger:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Trigger Automation Repo
-        run: |
-          curl -X POST \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{ secrets.API_TEST_TRIGGER_TOKEN }}" \
-          https://api.github.com/repos/roshaniwagh/api.swagh.in/dispatches \
-          -d '{"event_type":"run-api-tests"}'
+    if [ "$RESPONSE" != "204" ]; then
+      echo "Dispatch failed!"
+      exit 1
+    fi
