new project

diff --git a/.github/workflows/trigger-api-tests.yml b/.github/workflows/trigger-api-tests.yml
--- a/.github/workflows/trigger-api-tests.yml
+++ b/.github/workflows/trigger-api-tests.yml
@@ -1,15 +1,27 @@
-- name: Trigger Automation Repo
-  run: |
-    RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST \
-      -H "Accept: application/vnd.github+json" \
-      -H "Authorization: Bearer ${{ secrets.API_TEST_TRIGGER_TOKEN }}" \
-      https://api.github.com/repos/roshaniwagh/api.swagh.in/dispatches \
-      -d '{"event_type":"run-api-tests"}')
+name: Trigger API Automation
 
-    echo "HTTP Status: $RESPONSE"
-    cat response.txt
+on:
+  push:
+    branches:
+      - master   # change if your branch is main
 
-    if [ "$RESPONSE" != "204" ]; then
-      echo "Dispatch failed!"
-      exit 1
-    fi
+jobs:
+  trigger:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Trigger Automation Repo
+        run: |
+          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.API_TEST_TRIGGER_TOKEN }}" \
+            https://api.github.com/repos/roshaniwagh/api.swagh.in/dispatches \
+            -d '{"event_type":"run-api-tests"}')
+
+          echo "HTTP Status: $RESPONSE"
+          cat response.txt
+
+          if [ "$RESPONSE" != "204" ]; then
+            echo "Dispatch failed!"
+            exit 1
+          fi
